name: ci-golanng-workflow
on: [push]
jobs:
  check-application: 
    run: 
      runs-on: debian-latest
      steps: 
        - uses: actions/checkout@v2 
        - uses: actions/setup-go@v2
          with:
           - go-version: '1.20'
        - run: go test
        - run: go run math.go